### ISSUE TITLE
Write about the Dataset

### ISSUE THREAD

**Issue by Monzyy** [Joklost/P5-tex#13]

**Comment by Monzyy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Describe the dataset](https://trello.com/c/HlnLNo8l/10-describe-the-dataset)

**Comment by Joklost** [comment]
Added to section about identifying problems in https://github.com/Joklost/P5-tex/commit/4658b49665e1401085c634235f4ae1b38d43efb6.
