### ISSUE TITLE
Recommendation methods for design

### ISSUE THREAD

**Issue by GingerV1k1ng** [Joklost/P5-tex#16]

**Comment by GingerV1k1ng** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Recommendation methods](https://trello.com/c/1FEiGkcm/25-recommendation-methods)

**Comment by Joklost** [comment]
Merged.

**Comment by GingerV1k1ng** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Klustering IT2](https://trello.com/c/s37OI22E/41-klustering-it2)

**Comment by GingerV1k1ng** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Design IT2](https://trello.com/c/LbSLABnR/46-design-it2)

**Comment by GingerV1k1ng** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Recommendation methods](https://trello.com/c/4hjD8tNC/47-recommendation-methods)
