### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by timiane** [Joklost/P5-tex#3]
doing spell check section

**Comment by timiane** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nAM2NQKZ&#x2F;21-section-on-spell-check"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Section on Spell check</a>

**Comment by Joklost** [comment]
Add a subsection for a partial conclusion
