### ISSUE TITLE
Write about map reduce

### ISSUE THREAD

**Issue by pgug** [Joklost/P5-tex#6]

**Comment by Joklost** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;30f0kS87&#x2F;19-section-on-mapreduce"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Section on Mapreduce</a>

**Comment by Joklost** [comment]
See #22
