### ISSUE TITLE
Search Engines

### ISSUE THREAD

**Issue by Monzyy** [Joklost/P5-tex#7]
Write about search engines, and how it can be relevant for the reddit dataset

**Comment by Joklost** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;NX9RS4jO&#x2F;22-section-on-search-engines"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Section On Search Engines</a>
